hepsi:   derle calistir

derle:
		g++ -I ./include/ -o ./lib/BinarySearchTree.o -c ./src/BinarySearchTree.cpp
		g++ -I ./include/ -o ./lib/ListMover.o -c ./src/ListMover.cpp
		g++ -I ./include/ -o ./lib/LinkedList.o -c ./src/LinkedList.cpp
		g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
		g++ -I ./include/ -o ./bin/Test ./lib/Node.o ./lib/BinarySearchTree.o ./lib/ListMover.o ./lib/LinkedList.o ./src/Test.cpp

calistir:
	./bin/test